spring.application.name=Diet-Backend
spring.datasource.url=jdbc:postgresql://localhost:5432/dietdb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# System configuration
app.dietitian.email=suhedaterat2@gmail.com

# Spring Mail (E-posta Gönderim) Ayarları
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=canerturgut34@gmail.com
# NOT: Buraya Gmail hesabınızın "Uygulama Şifresi"ni (App Password) yazmalısınız.
spring.mail.password=ildoqpqfqtyowcpg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Database initialization clean flag
app.db.init-clean=false

